# Generated by Django 4.0.2 on 2022-04-20 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='social',
            old_name='name',
            new_name='fb',
        ),
        migrations.AddField(
            model_name='social',
            name='add',
            field=models.CharField(db_index=True, default='İsim Giriniz.', max_length=20, verbose_name='Ekleyen'),
        ),
        migrations.AddField(
            model_name='social',
            name='insta',
            field=models.CharField(db_index=True, default=21, max_length=20),
            preserve_default=False,
        ),
    ]
