# Generated by Django 4.0.2 on 2022-04-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0002_rename_name_social_fb_social_add_social_insta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
