# Generated by Django 4.0.2 on 2022-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='staffName',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='staffName2',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='staffName3',
            field=models.CharField(db_index=True, default=21, max_length=200),
            preserve_default=False,
        ),
    ]
