# Generated by Django 4.0.2 on 2022-04-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marine', '0005_about_staffname_about_staffname2_about_staffname3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staffName',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staffName2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staffName3',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff_number',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff_number2',
        ),
        migrations.RemoveField(
            model_name='about',
            name='staff_number3',
        ),
    ]
